<?php
/**
 * WordPress cleanup and config
 **/

declare( strict_types=1 );

namespace ParkdaleWire\OllieChild;

defined( 'ABSPATH' ) || exit;


add_action( 'after_setup_theme', __NAMESPACE__ . '\add_image_sizes' );
/**
 * Add image sizes.
 *
 * @return void
 */
function add_image_sizes() {
	add_image_size( 'pwire-480', 480 );
	add_image_size( 'pwire-640', 640 );
	add_image_size( 'pwire-896', 896 );
	add_image_size( 'pwire-1280', 1280 );
}


add_filter( 'image_size_names_choose', __NAMESPACE__ . '\add_image_sizes_to_editor' );
/**
 * Add custom images sizes to the editor.
 *
 * @param $sizes
 *
 * @return array
 */
function add_image_sizes_to_editor( $sizes ) {
	return $sizes + [
			'pwire-480' => 'Medium 480',
		];
}


add_filter( 'wp_editor_set_quality', __NAMESPACE__ . '\uploads_modify_quality', 20, 3 );
/**
 * Updates the quality of WebP and AVIF image sizes generated by WordPress.
 *
 * @param int    $quality   Quality level between 1 (low) and 100 (high).
 * @param string $mime_type Image mime type.
 *
 * @return int The updated quality for mime types.
 * @since 1.0.0
 *
 */
function uploads_modify_quality( int $quality, string $mime_type, array $size = [] ): int {
	$w = isset( $size['width'] ) ? (int) $size['width'] : 0;

	if ( 'image/avif' === $mime_type ) {
		return $w && $w <= 800 ? 65 : 50;
	}

	if ( 'image/webp' === $mime_type ) {
		return $w && $w <= 800 ? 82 : 75;
	}

	return $quality;
}


add_filter( 'body_class', __NAMESPACE__ . '\prune_body_classes', 20 );
/**
 * Remove some body classes
 *
 * @param array $classes
 *
 * @return array
 * @noinspection PhpVariableIsUsedOnlyInClosureInspection
 */
function prune_body_classes( array $classes ): array {

	$drop_exact = [
		'page-template',
		'post-template',
		'wp-custom-logo',
		'no-customize-support',
	];

	$drop_prefixes = [
		'wp-theme-',
		'wp-child-theme-',
		'page-id-',
		'postid-',
		'parent-pageid-',
		'single-format-',
	];

	$drop_patterns = [
		'-template-',
	];

	/** @noinspection PhpVariableIsUsedOnlyInClosureInspection */
	return array_values(
		array_filter(
			$classes,
			static function ( $class ) use ( $drop_exact, $drop_prefixes, $drop_patterns ) {

				if ( in_array( $class, $drop_exact, true ) ) {
					return false;
				}

				foreach ( $drop_prefixes as $prefix ) {
					if ( str_starts_with( $class, $prefix ) ) {
						return false;
					}
				}

				foreach ( $drop_patterns as $substring ) {
					if ( str_contains( $class, $substring ) ) {
						return false;
					}
				}

				return true;
			}
		)
	);
}


add_action( 'init', __NAMESPACE__ . '\disable_emojis', 20 );
/**
 * Disable wp emoji assets. Based on Autoptimize autoptimizeExtra.php
 *
 * @return void
 */
function disable_emojis(): void {
	remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
	remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
	remove_action( 'embed_head', 'print_emoji_detection_script' );
	remove_action( 'login_head', 'print_emoji_detection_script', 7 );

	remove_action( 'wp_print_styles', 'print_emoji_styles' );
	remove_action( 'admin_print_styles', 'print_emoji_styles' );
	remove_action( 'embed_head', 'print_emoji_styles' );
	remove_action( 'login_head', 'print_emoji_styles' );

	remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
	remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
	remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );

	add_filter( 'tiny_mce_plugins', static function ( array $plugins ): array {
		return array_values( array_diff( $plugins, [ 'wpemoji' ] ) );
	} );
}


add_filter( 'pre_wp_get_loading_optimization_attributes', __NAMESPACE__ . '\fetchpriorityhigh_exclude_header_images', 10, 4 );
/**
 * Prevent large SVGs in the mobile menu "stealing" fetch priority from hero images.
 *
 * Note: header logo SVGs should be under the square-pixels threshold of 50,000 anyway (e.g., < about 300 x 160), but
 * if they're not, this fixes it.
 *
 * @param string $context The rendering context.
 *
 * @return array|false Modified attributes array to override defaults or false to allow WordPress to continue default
 *                     behavior.
 */
function fetchpriorityhigh_exclude_header_images( $loading_attrs, $tag_name, $attr, string $context ): array|false {

	if ( 'template_part_' . WP_TEMPLATE_PART_AREA_HEADER === $context ) {
		// Purposefully omitting 'fetchpriority' => 'high'
		return [ 'decoding' => 'async' ];
	}

	return false;
}
